### PR TITLE
T5053 - Move postrm service hook to prerm

### PR DESCRIPTION
**Pull request by sempervictus**
Move `postrm` hook to a `prerm` such that the service it disables still exists (as it is removed with the package).

### CODE REVIEW

**Comment by sempervictus** [comment]
The CodeQL failure appears unrelated - i didn't change anything in the CPP files.

**Comment by burk3** [comment]
builds have been broken for me for a while from this. any way to get this landed? this seems like a fairly safe change.

**Review by dmbaturin — APPROVED** [review]
The change seems reasonable for me indeed.

**Comment by dmbaturin** [comment]
> builds have been broken for me for a while from this. any way to get this landed? this seems like a fairly safe change.

We need to fix that CodeQL stuff indeed.

**Review by c-po — APPROVED** [review]

**Pull request merged**
