### PR TITLE
Add helper function is_dhcp_4or6_enabled to replace is_dhcp_enabled

### PR DESCRIPTION
**Pull request by beamerblvd**
The function `is_dhcp_enabled` ignores DHCPv6. It is likely that many of
the uses of this function are not functioning properly, or functioning
only by luck, for DHCPv6 users. As DHCPv6 usage increases, the problems
will become more evident. This new function, `is_dhcp_4or6_enabled`,
should be safely and gradually migrated, checking that each replacement
does not break any functionality.

Additionally, `is_address_enabled` is incorrectly ignoring DHCPv6 as
well. I believe the risk to changing this function to be minimal,
as I could not find any actual uses of it. This change will safegaurd
future uses.

### CODE REVIEW

**Comment by njh** [comment]
Is this still relevant?

**Comment by dmbaturin** [comment]
Since we have moved all DHCP stuff away from the Perl code, I believe this shouldn't be needed. However, it also does no harm, and does seem to correct the behaviour of an existing function.

**Review by dmbaturin — APPROVED** [review]
Since we have moved all DHCP stuff away from the Perl code, I believe this shouldn't be needed. However, it also does no harm, and does seem to correct the behaviour of an existing function.

I would be hesitant to just close a PR that hasn't become broken, but I'm also (still) hesitant to merge a Perl feature that won't even see much use anymore. Please share your opinions.

**Comment by c-po** [comment]
Looking throughout the code (VyOS 1.4)

```bash
cpo@LR1.wue3:~$ grep -r is_address_enabled  /opt
/opt/vyatta/sbin/vyatta-interfaces.pl:  is_address_enabled is_dhcp_enabled is_ip_v4_or_v6);
/opt/vyatta/share/perl5/Vyatta/Misc.pm:                 is_address_enabled is_dhcp_enabled get_ipaddr_intf_hash
/opt/vyatta/share/perl5/Vyatta/Misc.pm:sub is_address_enabled {
```

```bash
cpo@LR1.wue3:~$ grep -r vyatta-interfaces.pl /opt | grep -v show | grep -v check
/opt/vyatta/sbin/vyatta-address:            exec /opt/vyatta/sbin/vyatta-interfaces.pl --dev="$2" --dhcp=start
/opt/vyatta/sbin/vyatta-address:            exec /opt/vyatta/sbin/vyatta-interfaces.pl --dev="$2" --dhcp=stop
/opt/vyatta/sbin/vyatta-interfaces.pl:# Module: vyatta-interfaces.pl
/opt/vyatta/sbin/vyatta-interfaces.pl:  $output  = "#\n# autogenerated by vyatta-interfaces.pl on $date\n#\n";
/opt/vyatta/share/vyatta-cfg/templates/zone-policy/zone/node.tag/interface/node.def:create: /opt/vyatta/sbin/vyatta-interfaces.pl --dev=$VAR(@) --warn
/opt/vyatta/share/vyatta-op/templates/release/dhcp/interface/node.tag/node.def:run: sudo /opt/vyatta/bin/sudo-users/vyatta-interfaces.pl --dhcp release --dev "$4"
```

I can see no place where this is referenced in the 1.4 and 1.3 codebase. It might only be relevant for VyOS 1.2

**Comment by dmbaturin** [comment]
With the code in question completely replaced and 1.2.x approaching its EOL, this will be dead code. We appreciate efforts of all contributors and this shouldn't discourage future contributions though!

**Pull request closed without merging**
