### PR TITLE
Docker: T5076: add script to install dependencies and build

### PR DESCRIPTION
**Pull request by jestabro**
Following T5076, add script to install dependencies and run build command. The change to the Jenkinsfile has not been tested in CI, yet. Pending PRs for vyatta-cfg will need this in place before merging.

### CODE REVIEW

**Comment by c-po** [comment]
Actually this change is not required as the dependency installation is done in the bade cloneAndBuild livrary of vyos-build/var.

It picks up all dependencies from the debian/control file

**Comment by jestabro** [comment]
Ah, thanks @c-po; I thought you might have a mechanism in place. How about for those building their own packages ? Should we provide a build script, or leave it to a manual install ? What do you think ?

**Comment by c-po** [comment]
> Ah, thanks @c-po; I thought you might have a mechanism in place. How about for those building their own packages ? Should we provide a build script, or leave it to a manual install ? What do you think ?

As we migrate more and more packages we should keep this a manual step. The dependencies for the most common packages (Kernel, libvyosconfig and vyos-1x) are shipped still via the container. Debloating only happened to less frequent build packages

**Comment by jestabro** [comment]
Closed as unneeded.

**Pull request closed without merging**
